
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: dev-to
data:
  DATABASE_SERVER_NAME: "db-payment"
  DATABASE_USER_NAME: "admin"
  DATABASE_USER_PASSWORD: "admin"
  DATABASE_NAME: "payment"
  DATABASE_PORT: "5433"
  SCHEMA_REGISTRY: "schema-registry"
  KAFKA_BROKERS: "broker"
  KAFKA_BOOTSTRAP_SERVERS: "broker:9092"
#  JAVA_OPTS: "--enable-preview -agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n -XX:MaxRAMPercentage=80"
  JAVA_OPTS: "--enable-preview -XX:MaxRAMPercentage=80"