apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: dev-to
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
      metadata:
        labels:
          app: payment
      spec:
        containers:
          - name: payment
            image: java-payment:latest
            imagePullPolicy: Never
            ports:
              - containerPort: 8082
                name: http
            envFrom:
              - configMapRef:
                  name: payment
            resources:
              requests:
                memory: "512Mi"
                cpu: "0.5"
              limits:
                memory: "512Mi"
                cpu: "1"