apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: dev-to
spec:
  ports:
    - port: 29092
      name: plaintext
    - port: 9092
      name: jmx
  selector:
    app: broker
  clusterIP: None