apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: dev-to
spec:
  ports:
    - port: 29092
      name: metric
    - port: 9092
      name: listner
  selector:
    app: kafka
  clusterIP: None