apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: dev-to
spec:
  ports:
    - port: 29092
      name: broker
    - port: 9092
      name: listner
  selector:
    app: broker
  clusterIP: None